Add friends likes
DavidovichIvan/java-filmorate pull request #7
Opened 2023-05-06 10:10 UTC by DavidovichIvan

Спасибо за ревью.

2023-05-06 17:28 UTC, EugeneLenkevich requested changes
Привет, Иван, спасибо за PR

В целом все отлично :)
Единственное, проследи, пожалуйста, за тем как распределяются обязанности по слоям, оставилнесколько коментариев. Основной смысл - хранение обработка и отбор данных - это хранилище, логика доменной области - сервисы, а контроллеры просто маршрутизируют запросы на сервисы

2023-05-06 17:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.getFilmStorage().addFilm(film);
Контроллер все же пусть зависит только от сервиса, а вот сервис зависит от хранилища (storage), тогда у нас будут слои: уровень контроллера, уровень бизнес-логики и уровень хранилища данных. Иначе у нас контроллер оказывается жестко связанным с деталями реализации нижележащих слоев. 
В общем, давай связь с storage отсюда уберем и будем к нему обращаться через методы сервиса  :)

По классике обязанности распределяются вот так

> Первый слой абстракции — это слой доступа к данным. В задачи данного слоя входит абстрагирование от базы данных. SQL-запросы к базе данных, в которой и хранятся данные приложения, скрываются за фасадом, который использует бизнес-слой.
> 
> Второй слой абстракции — это слой бизнес-логики. Он содержит объекты предметной области, а также функции для работы с ними. Эти функции и реализуют данную бизнес-логику.
> 
> Третий слой абстракции — это слой взаимодействия с пользователем. Данный слой включает компоненты пользовательского интерфейса.

2023-05-06 17:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else return filmStorage.getFilmsList().get(requestId);
filmStorage.getFilmsList().get(requestId);

Вот тут мы из сервиса лезем во внутренности хранилища, детали реализации же наоборот лчше прятать, почему бы не сделать метод в хранилище который  включаетв себя эту логику :)

2023-05-06 17:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        popularFilms.sort(Comparator.comparingInt(a -> a.getLikes().size()));
Сортировки выборки и пр тоде лучше делать на уровне хранилища, это его обязанности, на уровне сервиса у нас бизнес-логика :)

2023-05-06 17:28 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/InMemoryUserStorage.java
> +            User.setUserIdCounter(User.getUserIdCounter() - 1);
Не совсем понятно, а зачем менять какое то состояние в случае ошибки, нам точно надо учитывать неудачные попытки? :)

2023-05-07 08:17 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return filmService.getFilmStorage().addFilm(film);
По поводу уровней зависимостей контроллера/сервиса/хранилища понял;
когда делал изначально в каких-то методах пошел по пути наименьшего сопротивления.
Переделал в обоих контроллерах.

2023-05-07 08:18 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else return filmStorage.getFilmsList().get(requestId);
Работу с хранилищами перенес из сервисов. Смысл понятен, вся грязная работа должна быть на самом дне)
Постараюсь заострить внимание на этом, пока что не все моменты удается учитывать на автомате.

2023-05-07 08:18 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/InMemoryUserStorage.java
> +            User.setUserIdCounter(User.getUserIdCounter() - 1);
Наблюдение в точку, это избыточное действие, изначально не было у меня этого.
Но мне пришлось добавить чтобы пройти отдельные автотесты.
Некоторые тесты ожидают конкретный id фильма или юзера, что на мой взгляд глупость полная, так как сами тесты этот id не передают, отвечает за присвоение id сервер.
Я разобрался как выстроены тесты, пришлось искусствено скручивать id если запрос не прошел валидацию.
На фунционал никак не влияет.
Как альтернатива чтобы убрать скручивание счетчика id можно перенести увеличение id counter'а из конструктора в методы, после успешной валидации,
но мне такой подход нравится еще меньше и это опять таки нужно только чтобы пройти автотесты.
Я конечно только учусь, но с авторами автотестов в данной части я не согласен,
по сути получается, что автотест вменяет серверу какой должен быть id. Телега впереди лошади.

Абсолютно разумное замечание, которое я разделяю, прошу считать что этого кода нет).

2023-05-07 15:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else return filmStorage.getFilmsList().get(requestId);
Ну на самом деле в нашем тестовом примере это не так очевидно, логика простая и в принципе особой разницы не увидеть  если всю логику писать сразу в контроллерах, но, эта разница становится видной потом, когда появляется большое количество логики и надо вносит изменения в этот код. Если все смешанно то очень трудно бывает разобраться что там куда

2023-05-07 15:55 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/InMemoryUserStorage.java
> +            User.setUserIdCounter(User.getUserIdCounter() - 1);
Ох уж эти автотесты, ок :)

2023-05-07 15:57 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-06-09 06:03 UTC, merged