Add database
DavidovichIvan/java-filmorate pull request #8
Opened 2023-06-09 06:02 UTC by DavidovichIvan

2023-06-09 14:20 UTC, EugeneLenkevich commented
> Большая часть времени ушла не на код, как таковой, а на настройку базы данных и удовлетворение автотестов постмана

А чаще всего так и бывает :)

2023-06-09 14:27 UTC, EugeneLenkevich requested changes
Привет, Иван, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-06-09 14:27 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/UserDao.java
> +        for (User u : getAllUsers()) {
getAllUsers() 

два раза дергается метод, один раз наверно лишний :)

2023-06-10 07:24 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmControllerDB.java
> +        if (film.isEmpty()) {
Да, спасибо, изменил для FIlm и для User

2023-06-10 07:25 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenresControllerDB.java
> +    public GenresControllerDB(FilmServiceDB filmService) {
В этом месте переделал, в других оставил для наглядности для себя.

2023-06-10 07:25 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceDB.java
> +        int filmToPutLikeId = Integer.parseInt(filmId);
Перетряхнул все методы, выкинул строк 20-30 в итоге избыточных.

2023-06-10 07:26 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/UserDao.java
> +        for (User u : getAllUsers()) {
Да, посмотрел тут вообще весь метод лишний был, удалил его.

2023-06-10 07:27 UTC, DavidovichIvan commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/UserDao.java
> +        for (User u : firstUserFriends) {
Исполнено) При первичном написании я как-то на автомате по пути наименьшего сопротивления просто сделал на основании уже имеющихся методов.

Спасибо, все понятно. Чем дальше в лес тем страшнее)

2023-06-10 15:26 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/users/UserDao.java
> +        for (User u : firstUserFriends) {
> Чем дальше в лес тем страшнее)

Потом проще будет, когда появится общее понимание как это работает :)

2023-06-10 15:27 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-06-10 17:18 UTC, merged